### ISSUE TITLE
Softlock bugs

### ISSUE THREAD

**Issue by dfenwi** [sleepeybunney/maelstrom#23]
Hi,

Love the randomizer, and am on my third seed attempt. I have played through to Edea 1 (end of disc 1), and have encountered 2 bugs.

1. Odin replaces Diablos. This seems to work perfectly until the battle is over. Once it is over, when I open the menu, the battle restarts. This continues in perpetuity, making the menu inaccessible once the loop starts. I had intended to try it once I had finished Odin's replacement, but couldn't get that far due to bug 2.
2. Omega Weapon replaces Edea 1. Once Rinoa and Irvine rejoin the party, there is usually some on-screen dialogue before the battle starts in earnest. Rinoa and Irvine join the party and the camera cuts, but no dialogue shows. Once the camera resets to where it should be for the combat, the ATB does not start, and the game soft-locks.

The seed ID is 1414558946, with Rebalance bosses, free roam, and preset names turned off.

Thanks. #

**Comment by sleepeybunney** [comment]
Hi, thank you for taking the time to log this! Next time I'm able to work on the mod I'll see what I can do.

Number 1 is happening because it expects you to have unlocked the Diablos GF. I think the solution will be to move that reward to the replacement boss. Until then you may be able to continue if you can find the real Diablos elsewhere, or turn off boss shuffle before you use the lamp.

Number 2 I'll have to look into. I knew Edea 1 had problems but I assumed they would stick with her & not the encounter itself. The initial solution might be to just lock that encounter so it's always Edea. Again, you might be able to continue by turning off boss shuffle for that fight.

**Comment by dfenwi** [comment]
No rush on my part as I'm still enjoying playing it.

I had assumed that that would be the issue with #1. Only problem trying to test that myself was that Diablos replaced Ultima Weapon (and no way was I getting THAT before the end of disc 1).

Might I offer a possible reason for #2? I just generated another seed (Yes, I love it that much :D) where it shuffled Ifrit in place of Edea 1 and it worked perfectly. It may be that this specific combat expects dialogue, and searches the whole possible combat to find it. Since there isn't any for Omega Weapon, it soft locked.

Thanks again!

**Comment by Izumi-Chenmeiru** [comment]
I just had a similar thing happen with the lamp. I have the SeeD 948567380 and I received 20 magical lamps from a couple of bite bugs. I had gotten apocalypse magic in Fire Cavern so it was a relatively easy battle. After the battle however, I was taken to the party switch page. (I had received Edea by killing Ifrit's replacement already) The left side of the party switch menu was blank and the right side had Quistis, the game softlocked as soon as I moused over the slot I already had a Quistis in (the middle one). Might be a wonky effect of having another instance of the same party member, but it's just speculation from me. LMK if you'd like any more details! :)

**Comment by sleepeybunney** [comment]
Adel replacing Edea & locking up: https://clips.twitch.tv/PoliteEnergeticPartridgeFutureMan

After many hours of experimentation I've finally determined what triggers the event at the start: it's NOTHING.

It's not in the encounter file, the battle scene, anyone's battle script, the field script... I'm pretty sure it's hard-coded into the game engine itself that encounter 136 just does its own entire thing. Which is a bit scary. But it does suggest a solution...

**Comment by sleepeybunney** [comment]
Fixed Edea 1 by copying the whole thing into a new encounter & using that instead (164bb0c)

Looking at the lamp next

**Comment by sleepeybunney** [comment]
Fixed the lamp by awarding the Diablos GF when you beat whatever's inside it (4211522).

I mean _technically_ the bug is still there - it still tries to use the lamp again when you open the menu - but the outcome is different if you already have the GF. It'll cancel out one time & then leave you alone. (I think the real Diablos gets around it with some more hard-coding magic, so this is the best I can do for now)

I'll check out the party select thing as well but there's already a ticket to get that working properly (#13) so I'll close this & deal with it there.

Thanks again everyone!
