### ISSUE TITLE
Seifer (3rd)/Edea (2nd) Boss Softlock

### ISSUE THREAD

**Issue by endegrim** [sleepeybunney/maelstrom#60]
Edea (2nd) boss fight (replacing Raijin/Fujin (2nd) became a softlock, as Seifer (3rd) replaced an earlier boss (Oilboyles and Diabolos). Because Seifer was already defeated (I assume this is why) he didn't spawn into the Edea (2nd) fight and there was no way to target Edea as that boss requires Seifer be defeated before Edea is targetable.

Seed number was 1418834719 and I was playing on version 0.5 if that's any help.

**Comment by sleepeybunney** [comment]
Edea 2 was also replacing Tonberry King on this seed, and for that fight the boss is supposed to start hidden. Maelstrom mistakenly applied this behaviour to _both_ fights, so Seifer was stuck waiting to be spawned in by a Tonberry (which isn't likely to happen on Fujin/Raijin 2).

This is fixed by 2d3f89f which will be in v0.6
